/* File: hipe_literals.h, generated by /home/lyne/Downloads/otp_src_17.5/bin/i686-pc-linux-gnu/hipe_mkliterals.smp */
#ifndef __HIPE_LITERALS_H__
#define __HIPE_LITERALS_H__

#define F_TIMO 4
#define FREASON_TRAP 256
#define THE_NON_VALUE 0
#define EFE_NATIVE_ADDRESS 40
#define EFE_REFC 52
#define EFT_THING 0
#define BSF_ALIGNED 1
#define PB_ACTIVE_WRITER 2
#define PB_IS_WRITABLE 1
#define MB_ORIG 0
#define MB_BASE 4
#define MB_OFFSET 8
#define MB_SIZE 12
#define PROC_BIN_THING_WORD 0
#define PROC_BIN_BINSIZE 4
#define PROC_BIN_NEXT 8
#define PROC_BIN_VAL 12
#define PROC_BIN_BYTES 16
#define PROC_BIN_FLAGS 20
#define PROC_BIN_WORDSIZE 6
#define SUB_BIN_THING_WORD 0
#define SUB_BIN_BINSIZE 4
#define SUB_BIN_BITSIZE 12
#define SUB_BIN_OFFS 8
#define SUB_BIN_BITOFFS 13
#define SUB_BIN_WRITABLE 14
#define SUB_BIN_ORIG 16
#define SUB_BIN_WORDSIZE 5
#define HEAP_BIN_THING_WORD 0
#define HEAP_BIN_SIZE 4
#define HEAP_BIN_DATA 8
#define BINARY_ORIG_SIZE 12
#define BINARY_ORIG_BYTES 16
#define MAX_HEAP_BIN_SIZE 64
#define MS_THING_WORD 0
#define MS_MATCHBUFFER 4
#define MS_SAVEOFFSET 20
#define MS_MIN_SIZE 6
#define MB_ORIG_SIZE 4
#define MB_BASE_SIZE 4
#define MB_OFFSET_SIZE 4
#define MB_SIZE_SIZE 4
#define PROC_BIN_THING_WORD_SIZE 4
#define PROC_BIN_BINSIZE_SIZE 4
#define PROC_BIN_NEXT_SIZE 4
#define PROC_BIN_VAL_SIZE 4
#define PROC_BIN_BYTES_SIZE 4
#define PROC_BIN_FLAGS_SIZE 4
#define SUB_BIN_THING_WORD_SIZE 4
#define SUB_BIN_BINSIZE_SIZE 4
#define SUB_BIN_BITSIZE_SIZE 1
#define SUB_BIN_OFFS_SIZE 4
#define SUB_BIN_BITOFFS_SIZE 1
#define SUB_BIN_WRITABLE_SIZE 1
#define SUB_BIN_ORIG_SIZE 4
#define HEAP_BIN_THING_WORD_SIZE 4
#define HEAP_BIN_SIZE_SIZE 4
#define HEAP_BIN_DATA_SIZE 4
#define BINARY_ORIG_SIZE_SIZE 4
#define BINARY_ORIG_BYTES_SIZE 1
#define MS_THING_WORD_SIZE 4
#define MS_SAVEOFFSET_SIZE 4
#define MSG_NEXT 0
#define ARM_LEAF_WORDS 16
#define ARM_NR_ARG_REGS 3
#define ARM_IS_BIG_ENDIAN 0
#define PPC_LEAF_WORDS 16
#define PPC_NR_ARG_REGS 4
#define AMD64_LEAF_WORDS 24
#define AMD64_NR_ARG_REGS 4
#define AMD64_HP_IN_REGISTER 1
#define AMD64_HEAP_POINTER 15
#define X86_LEAF_WORDS 24
#define X86_NR_ARG_REGS 3
#define X86_NR_RET_REGS 3
#define X86_HP_IN_ESI 1
#define SPARC_LEAF_WORDS 16
#define SPARC_NR_ARG_REGS 4
#define P_OFF_HEAP_FUNS 304
#define EFT_NEXT 8
#define EFT_CREATOR 24
#define EFT_FE 4
#define EFT_NATIVE_ADDRESS 12
#define EFT_ARITY 16
#define EFT_NUM_FREE 20
#define EFT_ENV 28
#define ERL_FUN_SIZE 7
#define P_SCHED_DATA 412
#define P_FP_EXCEPTION 68
#define ERTS_IS_SMP 1
#define ERTS_NO_FPE_SIGNALS 1
#define MSG_MESSAGE 8
#define P_HP 40
#define P_HP_LIMIT 44
#define P_OFF_HEAP_FIRST 304
#define P_MBUF 316
#define P_ID 0
#define P_FLAGS 188
#define P_FVALUE 192
#define P_FREASON 196
#define P_FTRACE 200
#define P_FCALLS 168
#define P_BEAM_IP 160
#define P_ARITY 120
#define P_ARG0 132
#define P_ARG1 136
#define P_ARG2 140
#define P_ARG3 144
#define P_ARG4 148
#define P_ARG5 152
#define P_NSP 72
#define P_NCALLEE 84
#define P_CLOSURE 88
#define P_NSP_LIMIT 76
#define P_CSP 104
#define P_NARITY 108
#define P_FLOAT_RESULT 112
#define P_MSG_FIRST 216
#define P_MSG_SAVE 224
#define HIPE_LITERALS_CRC 77499794U
#define HIPE_SYSTEM_CRC 23244587U

#define RTS_PARAMS_CASES \
	case 1: value = 304; break; \
	case 4: value = 8; break; \
	case 5: value = 24; break; \
	case 6: value = 4; break; \
	case 7: value = 12; break; \
	case 8: value = 16; break; \
	case 9: value = 20; break; \
	case 10: value = 28; break; \
	case 11: value = 7; break; \
	case 12: value = 412; break; \
	case 14: value = 68; break; \
	case 15: value = 1; break; \
	case 16: value = 1; break; \
	case 19: value = 8; break; \
	case 22: value = 40; break; \
	case 23: value = 44; break; \
	case 24: value = 304; break; \
	case 25: value = 316; break; \
	case 26: value = 0; break; \
	case 27: value = 188; break; \
	case 28: value = 192; break; \
	case 29: value = 196; break; \
	case 30: value = 200; break; \
	case 31: value = 168; break; \
	case 32: value = 160; break; \
	case 33: value = 120; break; \
	case 34: value = 132; break; \
	case 35: value = 136; break; \
	case 36: value = 140; break; \
	case 37: value = 144; break; \
	case 38: value = 148; break; \
	case 39: value = 152; break; \
	case 40: value = 72; break; \
	case 41: value = 84; break; \
	case 42: value = 88; break; \
	case 43: value = 76; break; \
	case 44: value = 104; break; \
	case 45: is_defined = 0; break; \
	case 46: value = 108; break; \
	case 47: value = 112; break; \
	case 48: is_defined = 0; break; \
	case 49: value = 216; break; \
	case 50: value = 224; break;
#endif
